# vim:ts=2:sw=2:et

dist: precise

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer update --dev
  - mkdir -p test/build/coverage-xml

script:
  - export CODACY_PROJECT_TOKEN=97a4a7affeca4ca1ae10b890899e2835
  - ./vendor/bin/phpunit test/link_finder_test.php --coverage-clover test/build/coverage-xml/clover.xml
  - ./vendor/bin/codacycoverage clover test/build/coverage-xml/clover.xml
